### ISSUE TITLE
jscodeshift fails to parse strict-type-args.js

### ISSUE THREAD

**Issue by jedwards1211** [flowtype/flow-codemod#4]
I just installed latest jscodeshift today.

jscodeshift: 0.3.25
 - babel: 5.8.38
 - babylon: 6.8.3
 - flow: 0.26.0

I get a bunch of errors like this:

```
$ jscodeshift -t flow-codemod/transforms/strict-type-args/strict-type-args.js toy-factory-tracker --errors=toy-factory-tracker/flowerrors.json --extensions=js,jsx,flow
Processing 23036 files... 
Spawning 7 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
/Users/andy/.nvm/versions/node/v5.5.0/lib/node_modules/jscodeshift/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

SyntaxError: /Users/andy/flow-codemod/transforms/strict-type-args/strict-type-args.js: The keyword 'interface' is reserved (21:0)
  19 | // minimal API type info in lieu of full libdef
  20 | //
> 21 | interface Collection {
     | ^
```

**Comment by jedwards1211** [comment]
Do the maintainers have a `.babelrc` lurking in a parent directory?

**Comment by mroch** [comment]
this may be because jscodeshift uses babel5 which has an outdated parser. this is mentioned in the [README](https://github.com/flowtype/flow-codemod/blob/master/transforms/strict-type-args/README.md), but doesn't say what things are known to not parse... not sure if this is one of them. @bhosmer?

**Comment by mroch** [comment]
oh, maybe i misread. this isn't even able to parse the transform? i thought you were saying it hit one of your files that it couldn't transform, not that the transform itself doesn't load.

**Comment by jedwards1211** [comment]
Right, I saw that note in the README but it's the codemod script itself that jscodeshift fails to parse.

**Comment by bhosmer** [comment]
Hi Andy - I think this is due to a (recent change in jscodeshift)[https://github.com/facebook/jscodeshift/commit/327f985598784e1e91615d78237ece490995d165]. I've [logged an issue](https://github.com/facebook/jscodeshift) there; if I haven't heard within the next day or so I'll add a stripped version of the transform here. Thanks for reporting this!

**Comment by gabelevi** [comment]
Personally, I worked around this with

```
npm install jscodeshift@0.3.20
```

but we definitely should fix this generally.

**Comment by bhosmer** [comment]
Updated `strict-type-args.js` to stripped version (original is in a `src` subdir - see [here](https://github.com/flowtype/flow-codemod/commit/5a49240ac7aa3d84808f5864815eb0f04b5b36c3)), so should run fine now. Let's revisit if `jscodeshift` makes it possible to pick up colocated `.babelrc`s.

**Comment by fkling** [comment]
jscodeshift v0.3.26 removes type annotations form the transformer again. Sorry!
